### ISSUE TITLE
Add Support for Amazon Elastic Container Registry (ECR)

### ISSUE THREAD

**Issue by michaelperel** [safe-waters/docker-lock#5]
- [ ] Follow the registry/acr.go code as closely as possible
- [ ] If you have access to ECR credentials for open source, add integration tests where credentials are encrypted vars in AZDO pipeline

**Comment by kokes** [comment]
I tried it for a bit here: https://github.com/safe-waters/docker-lock/compare/master...kokes:ecr

But I hit a few issues:

- The registry URL is unique for each account (there's an `account_id` prefix), but I can't quite locate the ID in the environment very well (without shelling out to a utility, `awscli`). But I can look it up in the `configFile`, so that's what I did
- the `v2.go` code doesn't check status codes of HTTP requests, so I was running circles for a bit before I realised I wasn't properly authorized (fixed this)
- I just can't quite get the token right. I even gave up on AWS' HTTP API and used the aws CLI to get a token the ugly way... but that still didn't work right, getting 401s - maybe we need the sig v4 auth info on top of the token.

I've never quite worked with AWS' APIs without a library abstraction, so I'm not sure how to resolve this. I've added a few links and notes in the code.

**Comment by michaelperel** [comment]
Thanks for taking the time to investigate! As a headsup, I will be away from my computer until Monday for Thanksgiving holidays and will be able to work on ECR/better engage with your code and notes when I return.

For the first bullet, that is correct, the info is available in the config file.

For the second bullet, I need to publish a roadmap, but when the project was first written, everything (all parsers, etc.) were custom. This was to see the viability of the idea. In the last few weeks, I replaced most of the custom code with functions from moby and docker. Currently, the last "custom" piece is the registry. Instead, I hope to use functions in the docker go library to handle all registry auth, but I do not want to rely on a daemon being installed. I am hoping to release version 1.0, with as little custom code as possible soon.

For the third bullet, I haven't worked with AWS but will investigate the difference in their auth vs. ACR/other implemented registries.

Really appreciate your contributions and hope I can make the library work for your usecase :)

**Comment by michaelperel** [comment]
@kokes I had a chance to work on ECR. I have a working implementation in the branch `miperel/token-auth`. I have tested it in the ubuntu dev container (without a credstore) and on mac (with the credstore osxkeychain).

To test this out:

0. (For good measure...) Remove your previous `config.json`:
```
rm -rf ~/.docker/config.json
```

1. Login to docker: 
```bash
$ aws ecr get-login-password --region <YOUR_REGION> | docker login --username AWS --password-stdin <YOUR_ACCOUNT_ID>.dkr.ecr.<YOUR_REGION>.amazonaws.com
```

2. Install docker-lock from the branch:
```bash
git checkout miperel/token-auth
make install
```

3. Create a `Dockerfile` with an image on your ECR
```
FROM <YOUR_ACCOUNT_ID>.dkr.ecr.<YOUR_REGION>.amazonaws.com/<YOUR_IMAGE_NAME>
```

4. Create a file named `.env`
```
ECR_REGISTRY_NAME=<YOUR_ACCOUNT_ID>.dkr.ecr.<YOUR_REGION>
```

5. Create the Lockfile:
```
docker lock generate
```

In general, this is an example of token auth rather than using a username and password to login to docker. As I would like to support this for all registries, it has become clear that the registry layer needs refactoring (in line with the recent refactorings in master). I plan to do this in the upcoming weeks, and then release ECR support on master.

Thank you for noting the error handling. While this doesn't affect the use of `docker-lock` as a cli tool (because if something goes wrong in the registry layer, an error about not being able to find the digest bubbles up), it hinders it for development, makes it less clear, and makes it harder to use as a library in other projects. I will address that in the refactoring, and look to your notes to make sure I incorporate your feedback.

If you have any questions or thoughts, please let me know :)

**Comment by kokes** [comment]
@michaelperel cool stuff, just tested it against our live ECR in us-east-2 and it works as expected.

We ended up rolling [our own implementation](https://github.com/akamai/dlock) for several reasons (e.g. the Moby parser mangled some of our code - multiline commands get squished on a single line), but I'll be keeping docker-lock installed locally for other workflows.

**Comment by michaelperel** [comment]
@kokes Adding the Moby parser was a recent change. The goal was to make it easier to handle a ton of different edge cases, but I was unaware that it squished mulitiline commands into one line. This is definitely something that I will fix ASAP.

Otherwise, are there other reasons why you would make your own implementation? If you would be open to filing issues, I would love to improve this project, rather than have multiple similarly named projects out there with the same purpose.

**Comment by kokes** [comment]
The decision came down to the following issues with docker-lock.

1. Changes formatting (newlines, comments) - I submitted a PR for this last week, merged already
2. Changes command formatting (multiline commands) - I'll submit an issue about this
3. Doesn't support ECR - about to be resolved
4. Doesn't support our workflow where we don't leverage a lock file - we want to keep digests in our Dockerfiles, but we want to be able to bump them if there are newer ones upstream - submitted this as #65

**Comment by michaelperel** [comment]
I am going to revert using the changes that introduced the moby parser for rewriting (which will solve 1 more completely, and solve 2).

For number 4, I think that is a good idea and will look into it in.

Thanks for your comments and appreciate your engagement!

**Comment by michaelperel** [comment]
Number 1 & 2 have been fixed in #69 and has been released in v0.7.2

**Comment by michaelperel** [comment]
For anyone watching, discussion on Number 4 will continue on #65

**Comment by michaelperel** [comment]
@kokes I switched all registries to simply rely on [crane](https://github.com/google/go-containerregistry/blob/master/cmd/crane/README.md), so now all registries are supported.

All you need to do is login as you normally would (no need to have a special .env file), and this works with multiple sign ins and with any registry that you can properly sign into.

I cut a new release, v0.8.0
