### ISSUE TITLE
Multiline commands are not preserved

### ISSUE THREAD

**Issue by kokes** [safe-waters/docker-lock#68]
Given that the project leverages Moby's parser, we inherit some of its properties - e.g. the way it parses multiline commands - it eats the continuation backslashes at the parser level. When I looked at the AST, I couldn't retrieve enough information to reconstruct the original command. But I didn't spend too long on this.

Example:

If we run `docker lock generate && docker lock rewrite` on the following Dockerfile

```dockerfile
FROM busybox
ENTRYPOINT echo \
    foo \
    bar
```

we get

```diff
-FROM busybox
-ENTRYPOINT echo \
-    foo \
-    bar
+FROM busybox:latest@sha256:9f1c79411e054199210b4d489ae600a061595967adb643cd923f8515ad8123d2
+ENTRYPOINT echo     foo     bar
```

**Comment by michaelperel** [comment]
@kokes I fixed this by removing the moby parser from rewriting, and will cut a release v0.7.2 in a few minutes.
