### ISSUE TITLE
Docker lock rewrite does not work with mandatory variables in docker-compose file

### ISSUE THREAD

**Issue by andoks** [safe-waters/docker-lock#81]
**Description**
[Variables in docker-compose](https://docs.docker.com/compose/compose-file/#variable-substitution) file breaks `docker lock rewrite` with errors: `in 'docker-compose.yml', invalid interpolation format for services.hello_world.container_name: "required variable SOME_VAR is missing a value: error message". You may need to escape any $ with another $.`

**Repro**
https://github.com/andoks/variables_in_docker-compose_breaks_docker-lock
See run_repro.bash file in repo

**Version**
$ docker lock version
0.8.3

**Comment by michaelperel** [comment]
@andoks The fix is in master, I will cut a release likely tonight or tomorrow

**Comment by michaelperel** [comment]
@andoks The fix is in `v0.8.4`. Thanks for reporting the issue!

**Comment by andoks** [comment]
Tested v0.8.4 using the run_repro.bash script from https://github.com/andoks/variables_in_docker-compose_breaks_docker-lock, and docker-compose file is now updated as expected, thanks!
