### ISSUE TITLE
Docker lock rewrite fails when compose-file is located at different mount-point than /tmp

### ISSUE THREAD

**Issue by andoks** [safe-waters/docker-lock#82]
**Description**
`docker lock rewrite` fails with error "rename /tmp/docker-compose.yml-321063820 docker-compose.yml: invalid cross-device link". Seemingly happens when docker-compose file is located on a different mount from /tmp.

**Repro**
https://github.com/andoks/docker-compose_file_different_mount_than_tmp_breaks_docker-lock
See run_repro.bash file in repo

**Version**
$ docker lock version
0.8.3

**Comment by michaelperel** [comment]
@andoks Thank you for filing an issue!

Currently, docker-lock writes all files first to your computer's default temporary directory. Then it renames those files to the original files (which has the effect of replacing the original files with the newly written ones).

However, if your temporary directory is on another drive, this may fail with an error such as:
`rename /tmp/docker-compose.yml: invalid cross-device link`

To fix this, run `docker lock rewrite --tempdir .`, which means that the files will be temporarily written to a directory in your current directory. When docker-lock finishes rewriting, the temporary directory will be deleted.

This happens fast enough that you will never see the temporary directory.

Let me know if this fixes your issue, or if you would like to see any changes in the default behavior :)

**Comment by michaelperel** [comment]
@andoks In the most recent release `v0.8.4`, the default behavior is to write temporary paths to temporary folder in the current working directory. Therefore, you no longer need to use the `--tempdir` flag for this use case. Now you can just say, `docker lock rewrite` and everything will work.

**Comment by andoks** [comment]
@michaelperel: Great to hear, thanks!

I tested v0.8.4 with the run_repro.bash script from https://github.com/andoks/docker-compose_file_different_mount_than_tmp_breaks_docker-lock, and after the docker lock rewrite step, the docker-compose file is not changed. Am I doing something wrong?

**Comment by michaelperel** [comment]
@andoks Here is a gif where I run your repro steps in a container. Do you get a different result?

![rewrite2](https://user-images.githubusercontent.com/10049607/102377377-930fe680-3f92-11eb-8384-3516ef7c103d.gif)

**Comment by andoks** [comment]
I thought I did when I ran the repro as a script, sorry, my mistake: I ran the script, but it cd's into the tmp folder and when the script is done and exits, I am back at the original working dir, which indeed has not change (and should not have changed, since docker lock rewrite was executed in the copy in shm). It indeed works now :+1:
