### ISSUE TITLE
Suggestion: expand default glob for finding dockerfiles and compose-files

### ISSUE THREAD

**Issue by andoks** [safe-waters/docker-lock#90]
Currently it seems like docker-lock only looks for files called "Dockerfile" (in the case of dockerfiles) and files called "docker-compose.yml" (in the case of docker-compose files). Could it perhaps be a good idea to expand this to also include files that end with ".dockerfile" and ".docker-compose.yml" in cases where projects have multiple of these files in the same directory and need to differentiate them by name?

This is currently covered by the --dockerfile-globs --composefile-globs, so this is not strictly necessary. More a QoL change.

**Comment by andoks** [comment]
It seems to update docker-files which are not called "Dockerfile" if they are referenced through a build-stanza in a docker-compose file that it picks up however.

**Comment by michaelperel** [comment]
@andoks Currently there are a variety of default paths that are used for Dockerfiles, docker-compose files and kubernetes manifests. These are also used when recursively searching directories. The exact paths are specified in the README.

I think a good solution could be to have a cli flag where you could specify a regex that gets searched, so for your case `*.dockerfile.*`, or something along those lines.

**Comment by andoks** [comment]
@michaelperel: I must have overlooked that, sorry.

I think the existing globs flags already covers the necessary functionality as long as docker-lock stops choking on directories matching the filenames?

**Comment by michaelperel** [comment]
@andoks Closing this as I think the more powerful glob syntax in #91 should cover this usecase pretty easily. Thanks!
